### ISSUE TITLE
Trying to use on a folder with multiple subfolders, each of the folders contains one image

### ISSUE THREAD

**Issue by Duxmir** [caltechlibrary/handprint#46]
I am using this:

!handprint /s google ./save/

and getting this:

+-----------------------------------------------------------------------------+
|           Welcome to Handprint: HANDwritten Page RecognitIoN Test           |
+-----------------------------------------------------------------------------+
Given 10 images to work on.
Will apply results of 1 service: google
Will use credentials stored in 
C:\Users\sdunomir\AppData\Local\CaltechLibrary\Handprint/.
Will use up to 1 process threads.

Traceback (most recent call last):
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sdunomir\finished assignments for ML\handprint.exe\__main__.py", line 7, in <module>
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\site-packages\handprint\__main__.py", line 585, in console_scripts_main
    plac.call(main)
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\site-packages\plac_core.py", line 436, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\site-packages\plac_core.py", line 287, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\site-packages\handprint\__main__.py", line 550, in main
    alert_fatal(f'An error occurred ({ex_class.__name__}): {antiformat(str(ex))}')
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\site-packages\bun\ui.py", line 101, in alert_fatal
    ui.alert_fatal(text, *args, **kwargs)
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\site-packages\bun\cli.py", line 166, in alert_fatal
    self._print_or_queue(text.format(*args), style = 'fatal')
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\site-packages\bun\cli.py", line 127, in _print_or_queue
    self._console.print(text, style = style, highlight = False)
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\site-packages\rich\console.py", line 1655, in print
    self._buffer.extend(new_segments)
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\site-packages\rich\console.py", line 854, in __exit__
    self._exit_buffer()
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\site-packages\rich\console.py", line 812, in _exit_buffer
    self._check_buffer()
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\site-packages\rich\console.py", line 1960, in _check_buffer
    legacy_windows_render(
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\site-packages\rich\_win32_console.py", line 418, in write_styled
    self.write_text(text)
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\site-packages\rich\_win32_console.py", line 379, in write_text
    self.write(text)
  File "C:\Users\sdunomir\Miniconda3\envs\tf2\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-78: character maps to <undefined>

It seems like all the images are recognized, but them something seems to break... 
Thanks in advance

**Comment by mhucka** [comment]
It looks like this must be on Windows, based on the style of the path names.

The last error suggests there's something happening involving character sets, or possibly locales. Can you tell me more about the language you use and whether any of the file names might have special characters in them?

**Comment by ibrahim22020** [comment]
yea e gonna be regited a hunter ith ne target
 jaken hagar
